[package]
name = "thrustin"
version = "0.1.0"
authors = ["Max Chung, Alex Liu, Royce Sato"]
edition = "2018"

[dependencies]
lazy_static = "*"
rand = "*"
regex = "*"
remove_dir_all = "*"
rocket = "*"
ws = "*"