[package]
name = "thrustin"
version = "0.1.0"
authors = ["Max Chung, Alex Liu, Royce Sato"]
edition = "2018"

[dependencies]
lazy_static = "^1.3.0"
rand = "^0.6.5"
regex = "^1.1.6"
remove_dir_all = "^0.5.1"
rocket = "^0.4.1"
ws = "^0.8.1"