#!/bin/bash

# Remove existing log
rm /home/THRUSTIN/production/THRUST.log

# Set log location
exec 1>/home/THRUSTIN/production/THRUST.log 2>&1

# Show commands for clarity
set -x

# Kill existing server
sudo killall thrustin

# Undo any existing changes, possible through webpack bundle hashing
cd /home/THRUSTIN
git checkout .

# Get new updates
git pull
    
# Build frontend files in production
cd /home/THRUSTIN/frontend
# Install packages if needed
npm install
# Build in production mode
npm run build-prod

cd /home/THRUSTIN/backend
# Run server in release
# Build first so we can see progress in console output
# Need to specify full cargo path for some reason, probably can't set path correctly on reboot
/root/.cargo/bin/cargo build --release

# Run
nohup /root/.cargo/bin/cargo run --release &
